### PR TITLE
scoin-js - pay2tr and ScriptTree

### PR DESCRIPTION
**Pull request by VzxPLnHqr**
We should not merge this until it is more usable. Figured I would open the PR now though so that it will be easier to track the WIP.

Currently, this PR lets a javascirpt person put `<script src="https://unpkg.com/@vzxplnhqr/scoin/lib/scoin.bundle.js"></script>` in their html file and they can interact with a few `scoin` functions from javascript (with more on the way!).

For example:
```javascript

// two trivial hex-encoded bitcoin scripts
// script #1: 0x51 (OP_1)
// script #2: 0x52 (OP_2)

const scripts = ['51','52'] 

// build a taproot-aware merkle tree from these scripts
const tree = Scoin.ScriptTree.naiveFromList(scripts)

// calculate the merkle root
const merkleRoot = tree.hash

// an unspendable public key (thereby disabling key path spending)
const internalPubKey = '50929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0'

// use the merkleRoot and the unspendable public key
// to create a taproot output with key path spend disabled
const scriptpubkey = Scoin.Script.pay2tr(internalPubKey,merkleRoot)

```

### CODE REVIEW

**Comment by VzxPLnHqr** [comment]
continuing from example in description above, the following now works:
```javascript
// get the merkle proofs for each script in the tree
const proofs = tree.merkleProofs

// verify the merkle proof for the first script
tree.verifyProof(script[0], proofs[0].proof)
```

**Comment by VzxPLnHqr** [comment]
I will stop on the javascript wrapper thing for now until when/if some javascript person (@supertestnet ???) actually wants to use it. Then we can use this thread to figure out the bare minimum remaining functions necessary to complete the interop API, for constructing and spending taproot/tapscript outputs.

For example, here are some functions that either need to be exposed from `scoin` into javascript land or the caller needs to have ready access to similar functions in other javascript libraries:
1. `encodeWitnessAddress` - turn the (hex) of the taproot output into a bech32m address for easy funding.
2. `Transaction.hashForSigning(tx)` - to get a message to schnorr sign
3. ....

**Comment by VzxPLnHqr** [comment]
If there is a goal of being able to do `Musig2` from javascript to spend a `pay2tr` output, #25 is an outline/test of what we would need to expose to javascript to do that.

**Comment by VzxPLnHqr** [comment]
Closing until when/if there is more demand for this. At least the scaffolding is in place already now.

**Comment by fiatjaf** [comment]
I think it was very good that we started this.

**Pull request closed without merging**
